version: '3.8'

services:
  auth-service:
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_ENV=development

  appointment-service:
    volumes:
      - ./appointment-service:/app
    environment:
      - FLASK_ENV=development

  notification-service:
    volumes:
      - ./notification-service:/app
    environment:
      - FLASK_ENV=development

  frontend:
    volumes:
      - ./frontend:/app
    environment:
      - FLASK_ENV=development